### ISSUE TITLE
Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10 or later

### ISSUE THREAD

**Issue by lucifercr07** [lucifercr07/stream-service#3]
Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10 or later

**Comment by sharath2106** [comment]
@lucifercr07 I'd like to work on this.

**Comment by lucifercr07** [comment]
Thanks for fixing @sharath2106 , let me know if you want to contribute more in this project.

**Comment by sharath2106** [comment]
@lucifercr07 Yes. I'm interested in contributing to the project. Any possibility of having a weekly catchup where we can discuss things?

**Comment by lucifercr07** [comment]
We can have a zoom call bi/tri-weekly. Please let me know which day you'll be comfortable with. Also meanwhile you can go through the `Readme` and give any inputs you feel.

**Comment by sharath2106** [comment]
Definitely! I'll be comfortable having a call on the second and fourth Saturday of the month. And for the Readme, I'd like to raise issues and fix it if it needs to be or shall discuss it. Do you have a Slack channel?
